---
- name: Instalar UFW
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Politica padrao - negar entrada
  community.general.ufw:
    default: deny
    direction: incoming

- name: Politica padrao - permitir saida
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Liberar portas configuradas
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop: "{{ firewall_allowed_ports }}"

- name: Ativar UFW
  community.general.ufw:
    state: enabled
