name: Deploy Static Content to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "index.html" # Trigger only when index.html changes

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Allow the GITHUB_TOKEN to write to GitHub Pages
      id-token: write   # Allow the GITHUB_TOKEN to create an OpenID Connect (OIDC) token
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./" # Uploads the entire project directory as an artifact

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
