# Usa uma imagem base oficial do Netdata
FROM netdata/netdata:latest

# Define a porta padrão do Netdata
EXPOSE 19999

# Comando para iniciar o Netdata (já é o CMD padrão da imagem, mas incluído para clareza)
CMD ["/usr/sbin/netdata", "-D"]
